source 'https://github.com/CocoaPods/Specs.git'

def import_pods 
  pod 'Ambly', :path => '../../'
end

target :ios do
  platform :ios, '8.0'
  link_with 'Ambly Demo'
  import_pods
end

target :tvos do
  platform :tvos, '9.0'
  link_with 'Ambly Demo TV'
  import_pods
end
