source 'https://github.com/CocoaPods/Specs.git'

def import_pods 
  pod 'Ambly', :path => '../../'
end

target 'Ambly Demo' do
  platform :ios, '8.0'
  import_pods
end

target 'Ambly Demo TV' do
  platform :tvos, '9.0'
  import_pods
end

target 'Ambly Demo CLI' do
  platform :osx, '10.10'
  import_pods
end
